language: php
sudo: required

php:
  - 5.6
  - 7.0

env:
  - DB_USERNAME=root DB_PASSWORD=

services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database homestead;'

script:
  - composer install
  - "php -r \"copy('.env.example', '.env');\""
  - php artisan modules:migrate --seed
