language: php

php:
  - 5.6
  - 7.0

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry "php -r \"copy('.env.example', '.env');\""
