language: php
sudo: required

php:
  - 5.6
  - 7.0

env:
  - DB_USERNAME=root DB_PASSWORD=

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database homestead;'

install:
  - travis_retry composer install
  - travis_retry "php -r \"copy('.env.example', '.env');\""
  - travis_retry php artisan modules:migrate --seed
